#ifndef LIBACCELAPLATFORM_INCLUDE_ACCELA_PLATFORM_EVENT_WINDOWCLOSEEVENT_H
#define LIBACCELAPLATFORM_INCLUDE_ACCELA_PLATFORM_EVENT_WINDOWCLOSEEVENT_H

namespace Accela::Platform
{
    /**
     * OS event representing the engine's window being closed
     */
    struct WindowCloseEvent {};
}

#endif //LIBACCELAPLATFORM_INCLUDE_ACCELA_PLATFORM_EVENT_WINDOWCLOSEEVENT_H
